-- Migration: Add token_hotness table and remove is_hot column
-- Date: 2025-02-24

-- Drop is_hot column from tokens table
ALTER TABLE public.tokens
DROP COLUMN IF EXISTS is_hot;

-- Create token_hotness table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.token_hotness (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_mint TEXT REFERENCES public.tokens(mint),
    detected_at TIMESTAMPTZ DEFAULT NOW(),
    market_cap_usd NUMERIC NOT NULL,
    start_market_cap NUMERIC NOT NULL,
    liquidity_usd NUMERIC NOT NULL,
    cumulative_buy_volume NUMERIC NOT NULL,
    cumulative_net_volume NUMERIC NOT NULL,
    reason TEXT
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_token_hotness_token_mint_detected_at 
ON public.token_hotness(token_mint, detected_at);

-- Enable RLS on token_hotness table
ALTER TABLE IF EXISTS public.token_hotness ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for token_hotness
CREATE POLICY "Allow public read access to token_hotness"
    ON public.token_hotness FOR SELECT
    USING (true);

CREATE POLICY "Allow authenticated users to insert token_hotness"
    ON public.token_hotness FOR INSERT
    TO authenticated
    WITH CHECK (true);

-- Grant necessary permissions
GRANT ALL ON public.token_hotness TO authenticated;
GRANT ALL ON public.token_hotness TO service_role;
