-- Migration: Add social traction functionality
-- Date: 2025-03-31

-- Add social sentiment columns to token_hotness table
ALTER TABLE public.token_hotness 
ADD COLUMN IF NOT EXISTS positive_social_sentiment BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS last_social_check TIMESTAMPTZ;

-- Create token_social_traction table
CREATE TABLE IF NOT EXISTS public.token_social_traction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id BIGINT REFERENCES public.token_hotness(id),
    token_mint TEXT NOT NULL,
    fetched_at TIMESTAMPTZ DEFAULT NOW(),
    tweet_count INTEGER NOT NULL,
    retweet_count INTEGER NOT NULL,
    like_count INTEGER NOT NULL,
    traction_score NUMERIC NOT NULL,
    composite_score NUMERIC NOT NULL
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_token_social_traction_token_id_fetched_at 
ON public.token_social_traction(token_id, fetched_at);

-- Enable RLS on token_social_traction table
ALTER TABLE IF EXISTS public.token_social_traction ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for token_social_traction
CREATE POLICY "Allow public read access to token_social_traction"
    ON public.token_social_traction FOR SELECT
    USING (true);

CREATE POLICY "Allow authenticated users to insert token_social_traction"
    ON public.token_social_traction FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update token_social_traction"
    ON public.token_social_traction FOR UPDATE
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Grant necessary permissions
GRANT ALL ON public.token_social_traction TO authenticated;
GRANT ALL ON public.token_social_traction TO service_role;

-- Schedule fetch_social_traction to run every 30 minutes
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'fetch_social_traction') THEN
        PERFORM cron.unschedule('fetch_social_traction');
    END IF;
END $$;

SELECT cron.schedule(
    'fetch_social_traction',
    '*/30 * * * *',  -- Every 30 minutes
    $$
    SELECT net.http_post(
        url := 'https://mgdagmkhveyrshpbitdd.supabase.co/functions/v1/fetch-social-traction',
        headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nZGFnbWtodmV5cnNocGJpdGRkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MDM1MjczMywiZXhwIjoyMDU1OTI4NzMzfQ.KHNxbdCRpj1sFYd2fYSXVBQqLYHV25BC2IUM83VBeJU"}',
        body := '{}'
    ) AS request_id;
    $$
);
